$ANSIBLE_VAULT;1.1;AES256
34376638386562613533633432386134353766326561373262623931333538316537373265653765
3639303765616364336433396332373561316364366632330a333662656164666163396466653466
36303133343232353335343130356665636666666164356134386136353666613030373862633266
3065666532616635300a623838353165363134373730383630663737396363363537343466363063
38653562653862643434303638656161336435636365323435646433343038313439333866666530
63316534643231386135346533386563393363643637636432366139666432636232663630373763
34623537366134366237623763666337653732653932613439333831653532633763613935633536
33343937653666616161
