$ANSIBLE_VAULT;1.1;AES256
37373962363430303661666439376263383737663262616333363234643835663938656639313632
3539653232373632353533346230666262343034616363620a366535666234613531633166316162
33303634313831373836623535303363366233336238636366396634643637646532336331653837
3731396531303130330a633934663964653766663238666239343132333262366666306664653437
65666537633238336337333363316638653262323764643835393134646565613066313633386465
63303437633765393932666236343131643232323137306365356333383065633231343533333636
38653362356166316463646466396134306532663662623737623861333466633139353433623236
61636461376361363762
